const strings: Record<string, Record<string, string>> = {
  en: {
    a11yTitle: 'Accessibility Options',
    closePanel: 'Close Accessibility Menu',
    profilesSection: 'Accessibility Profiles',
    adjustersSection: 'Granular Adjustments',
    reset: 'Reset All Options',
    version: 'Portal v1.2.0',
    visuallyImpaired: 'Visually Impaired',
    visuallyImpairedDesc: 'High contrast, scaled text, large cursor',
    dyslexic: 'Dyslexic Font',
    dyslexicDesc: 'Specialized typeface for reading clarity',
    adhd: 'ADHD Friendly',
    adhdDesc: 'Focus tools and comfortable spacings',
    colorBlind: 'Color Blind Mode',
    colorBlindDesc: 'Custom filter for green/red weakness',
    cognitive: 'Cognitive Support',
    cognitiveDesc: 'Speech assist, highlighted targets & reduced motion safety',
    textScale: 'Text Size',
    fontDyslexic: 'Dyslexic Fonts',
    fontDyslexicDesc: 'Adapt font for dyslexic readability',
    contrast: 'Contrast Mode',
    contrastDefault: 'Default',
    contrastHigh: 'High Contrast (B&W)',
    contrastInverted: 'Inverted (W&B)',
    contrastDark: 'Dark Mode',
    contrastYellowNavy: 'Yellow on Navy',
    satMode: 'Saturation Control',
    satDefault: 'Default',
    satLow: 'Low Saturation',
    satHigh: 'High Saturation',
    satMono: 'Grayscale',
    cursorBig: 'Big Cursor',
    cursorBigDesc: 'Increase cursor size for visibility',
    spacingLetter: 'Letter Spacing',
    spacingLine: 'Line Spacing',
    letterSpacingDefault: 'Default',
    letterSpacingWide: 'Wide',
    letterSpacingWider: 'Wider',
    letterSpacingWidest: 'Widest',
    lineSpacingDefault: 'Default',
    lineSpacingComfortable: 'Comfortable',
    lineSpacingLoose: 'Loose',
    lineSpacingExtraLoose: 'Extra Loose',
    highlightLinks: 'Highlight Links',
    highlightLinksDesc: 'Add underline & borders to links',
    readSpeaker: 'Speech Co-Pilot',
    readSpeakerDesc: 'Read text aloud on hover/focus',
    seizureSafety: 'Seizure Safe Mode',
    seizureSafetyDesc: 'Stop flash risks & slow animation',
    adhdFocus: 'ADHD Reading Ruler',
    adhdFocusDesc: 'Add a sliding ruler to assist reading focus',
    cbMode: 'Color Blind Mode',
    cbNone: 'None',
    cbDeuteranopia: 'Deuteranopia',
    cbProtanopia: 'Protanopia',
    cbTritanopia: 'Tritanopia',
  },
  ar: {
    a11yTitle: 'خيارات سهولة الوصول',
    closePanel: 'أغلق قائمة سهولة الوصول',
    profilesSection: 'ملفات سهولة الوصول الجاهزة',
    adjustersSection: 'التعديلات التفصيلية',
    reset: 'إعادة تعيين كافة الخيارات',
    version: 'بوابة الإصدار 1.2.0',
    visuallyImpaired: 'ضعاف البصر',
    visuallyImpairedDesc: 'تباين عالٍ، تكبير النص، ومؤشر كبير',
    dyslexic: 'خط عسر القراءة',
    dyslexicDesc: 'تطبيق خطوط خاصة ومريحة للقراءة',
    adhd: 'صديق لـ ADHD',
    adhdDesc: 'أدوات التركيز البصري وتباعد مريح',
    colorBlind: 'حالة عمى الألوان',
    colorBlindDesc: 'تفعيل فلاتر تباين مخصصة لعمى الألوان',
    cognitive: 'الدعم المعرفي',
    cognitiveDesc: 'تمييز الروابط، القراءة الصوتية، وحركة آمنة',
    textScale: 'حجم النص',
    fontDyslexic: 'خط عسر القراءة',
    fontDyslexicDesc: 'تحسين شكل الخط ليسهل القراءة لمن يعانون من عسر القراءة',
    contrast: 'وضع التباين',
    contrastDefault: 'الافتراضي',
    contrastHigh: 'تباين عالٍ (أبيض وأسود)',
    contrastInverted: 'تباين معكوس (أسود وأبيض)',
    contrastDark: 'الوضع الداكن',
    contrastYellowNavy: 'أصفر على كحلي',
    satMode: 'التحكم بالتشبع',
    satDefault: 'الافتراضي',
    satLow: 'تشبع منخفض',
    satHigh: 'تشبع مرتفع',
    satMono: 'أحادي اللون (رمادي)',
    cursorBig: 'مؤشر كبير',
    cursorBigDesc: 'تكبير حجم مؤشر الماوس لزيادة وضوحه',
    spacingLetter: 'تباعد الأحرف',
    spacingLine: 'تباعد السطور',
    letterSpacingDefault: 'الافتراضي',
    letterSpacingWide: 'واسع',
    letterSpacingWider: 'أوسع',
    letterSpacingWidest: 'الأوسع',
    lineSpacingDefault: 'الافتراضي',
    lineSpacingComfortable: 'مريح',
    lineSpacingLoose: 'واسع',
    lineSpacingExtraLoose: 'واسع جداً',
    highlightLinks: 'تمييز الروابط',
    highlightLinksDesc: 'إضافة خطوط وحدود حول جميع الروابط النشطة',
    readSpeaker: 'المساعد الصوتي',
    readSpeakerDesc: 'نطق النصوص المكتوبة عند تمرير الماوس عليها',
    seizureSafety: 'حماية الصرع',
    seizureSafetyDesc: 'إلغاء التحريكات والوميض لضمان السلامة الكاملة',
    adhdFocus: 'محدد التركيز (ADHD)',
    adhdFocusDesc: 'إضافة مسطرة قراءة متحركة للتركيز البصري',
    cbMode: 'نوع عمى الألوان',
    cbNone: 'بلا',
    cbDeuteranopia: 'دوتيرانوبيا',
    cbProtanopia: 'بروتانوبيا',
    cbTritanopia: 'تريتانوبيا',
  },
};

export function getA11yString(lang: string, key: string): string {
  return strings[lang]?.[key] ?? key;
}
